[files]
extend-exclude = [
  "bun.lock",
  "node_modules/",
  "dist/",
  ".astro/",
  "*.min.js",
]

[default]
extend-ignore-re = [
  # Markdown frontmatter dates
  "publishDate:.*",
  "updatedDate:.*",
  # URLs
  "https?://[^\\s)\"'>]+",
  # HTML entities
  "&[a-z]+;",
  # Truncated description fields (word cut off before ...)
  "\\w+\\.\\.\\.['\"]*",
]

[default.extend-words]
# Author names
Wouters = "Wouters"
Brandl = "Brandl"
Hamel = "Hamel"
Deily = "Deily"
Durbin = "Durbin"
Hastings = "Hastings"
Kuchling = "Kuchling"
Galindo = "Galindo"
Driscoll = "Driscoll"
Jenvey = "Jenvey"
Langa = "Langa"
Ned = "Ned"
haypo = "haypo"
# Python/tech terms
pyc = "pyc"
pyo = "pyo"
repr = "repr"
compat = "compat"
noreply = "noreply"
# Common in migrated Blogger content
CNA = "CNA"
Sur = "Sur"
aboue = "aboue"
availabl = "availabl"
propper = "propper"
tha = "tha"
ths = "ths"
thi = "thi"
ba = "ba"
iff = "iff"
nd = "nd"
ons = "ons"
te = "te"
aways = "aways"
Pytho = "Pytho"
Ines = "Ines"
adminstration = "adminstration"
Receipient = "Receipient"
truely = "truely"
sponsoree = "sponsoree"
sponsorees = "sponsorees"
Sponsoree = "Sponsoree"
Sponsorees = "Sponsorees"
ove = "ove"
Chuks = "Chuks"
Accoring = "Accoring"
advices = "advices"
descrimination = "descrimination"
occassions = "occassions"
Calle = "Calle"
Leornardo = "Leornardo"
liason = "liason"
wich = "wich"
Foto = "Foto"
rasie = "rasie"
Univesity = "Univesity"
invigoratng = "invigoratng"
encouragred = "encouragred"
